language: elixir

dist: trusty
sudo: required

otp_release: 19.2
elixir:
  - 1.3.4
  - 1.4.0

env:
  matrix:
    - CASSANDRA_VERSION=2.2.8 AUTHENTICATION=true
    - CASSANDRA_VERSION=2.2.8
    - CASSANDRA_VERSION=3.9 AUTHENTICATION=true
    - CASSANDRA_VERSION=3.9
    - USE_SCYLLA=true SCYLLA_OPTS="--network-stack posix --enable-in-memory-data-store 1 --developer-mode 1" SCYLLA_OPTS_LOG="--log-to-stdout 1 --default-log-level info"

matrix:
  include:
    otp_release: 18.3
    elixir: 1.4.0
    env: CASSANDRA_VERSION=3.9

# These steps are taken from: http://cassandra.apache.org/doc/latest/getting_started/installing.html#installation-from-binary-tarball-files.
# Setps for Scylla taken from https://github.com/scylladb/gocqlx
before_install:
  - |-
     if [ $CASSANDRA_VERSION ]; then
       java -version
       wget https://archive.apache.org/dist/cassandra/$CASSANDRA_VERSION/apache-cassandra-$CASSANDRA_VERSION-bin.tar.gz
       tar -xzf apache-cassandra-$CASSANDRA_VERSION-bin.tar.gz
       if [ $AUTHENTICATION = true ]; then
         sed -i -e "s/\(authenticator: \)AllowAllAuthenticator/\1PasswordAuthenticator/" apache-cassandra-$CASSANDRA_VERSION/conf/cassandra.yaml
       fi
       sh apache-cassandra-$CASSANDRA_VERSION/bin/cassandra
       for try in {1..12}; do (nodetool version > /dev/null 2>&1 && break) || sleep 5; done
     fi
     if [ $USE_SCYLLA = true ]; then
       sudo curl -o /etc/apt/sources.list.d/scylla.list -L http://repositories.scylladb.com/scylla/repo/77c7dfe41d1ef5dc59e939ca5fd01b32/ubuntu/scylladb-2.0-trusty.list
       sudo apt-key update
       sudo apt-get -qq update
       sudo apt-get install -y --allow-unauthenticated scylla-server
       sudo /usr/bin/scylla --options-file /etc/scylla/scylla.yaml ${SCYLLA_OPTS} ${SCYLLA_OPTS_LOG} &
     fi
