language: elixir

dist: trusty
sudo: required

services:
  - docker

otp_release:
  - 19.2

elixir:
  - 1.4.5
  - 1.7.3

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.22.0
  matrix:
    - CASSANDRA_VERSION=2.2 SCYLLA_VERSION=2.0.0 AUTHENTICATION=true
    - CASSANDRA_VERSION=2.2 SCYLLA_VERSION=2.0.0
    - CASSANDRA_VERSION=3 SCYLLA_VERSION=2.3.0 AUTHENTICATION=true
    - CASSANDRA_VERSION=3 SCYLLA_VERSION=2.3.0

script:
  - docker-compose up -d
  - ./test/docker/healthcheck-dockers.sh
  - mix test.all

jobs:
  include:
    - stage: check formatted
      script: mix format --check-formatted
      otp_release: 19.2
      elixir: 1.7.3
      before_install: skip
      sudo: false

stages:
  - check formatted
  - test

before_install:
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m) > docker-compose
  - chmod +x docker-compose
  - docker-compose build
