version: '3'

services:
  database:
    build:
      context: ./test/docker
    ports:
      - "9042:9042"
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 20s
      timeout: 10s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: 50m
